### ISSUE TITLE
Scraper dla NIPU 

### ISSUE THREAD

**Issue by PhilipMichvong** [ITA-Flowers/Zostan_w_Swidnicy#20]
# Zadanie

Opracować webscrapera który dla danego nipu firmy. jeśli istnieje zwróci dane w formie ;

```
Czy_Istnieje : true
domena_firmy : @ORLEN.PL
``` 

Jeśli nie istnieje zwróci FALSE

**Comment by Baro-00** [comment]
### Zadanie anulowane
