### ISSUE TITLE
API Gateway - interfejs

### ISSUE THREAD

**Issue by Baro-coder** [ITA-Flowers/Zostan_w_Swidnicy#6]
## **Zadanie**

Opracować i zaimplementować zbiór punktów końcowych HTTP jako samodzielny program **Python Fast API** dla aplikacji klienckiej.

W komentarzu załączyć zbiór wzoróœ oczekiwanych żądań i odpowiedzi (patrz: przykład poniżej). 

### **GetCompanyByEmail**

**Endpoint**: `/api/company/get`

**Method**: `GET`

**Request Body**:

``` json
{
   "email" : "companyA@dp.com"
}
```

---

**Response `OK`**

**Status Code**: `200`

```json
{
   "companyName" : "...",
   "xxx": "xxx"
}
```

**Response `NOT FOUND`**

**Status Code**: `404`

```json
{
  "code": 404
  "message": "Resource not found."
}
```

**Comment by Baro-00** [comment]
### Zadanie anulowane
